### ISSUE TITLE
Info button on MenuBar

### ISSUE THREAD

**Issue by bawldiggle** [amritendu07/quicknote#5]
Does not show anything.
No info displayed

**Comment by amritendu07** [comment]
If you click Info button - 
![Screenshot_4](https://user-images.githubusercontent.com/13234071/75132266-54a3f500-56fc-11ea-8128-64adf9ea8fec.png)
If you click the sub-menu About
![Screenshot_5](https://user-images.githubusercontent.com/13234071/75132298-74d3b400-56fc-11ea-9c88-1c45d3629ecd.png)
